package com.zrt.pvz;

/**
 * @author 曾瑞庭
 * @Description:
 * @date 2023/11/24 15:48
 */
public enum EntityType {
    PLANT,ZOMBIE,WEEDER,SUNSHINE,EMPTY,SPACE,MAPPOINT,PLANTPREVIEW,SUNSHINECOLLECT,BULLET,SHOVEL,HOME,
    POWERBEAT,MOVEPOWERBEAT,POWERBEATCOLLECT,CHOOSEBUTTON,EMPTYVIEW,TEXTUREBUTTON,CHOSENBG,BOMB,TRIGGER
}
